# Generated by Django 4.2 on 2024-09-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.TextField()),
                ('destinatario', models.TextField()),
                ('contenido_mensaje', models.TextField()),
                ('hora', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
